volumes:
  pg_data:
  static:
  media:
  redoc:
  
networks:
  foodgram_network:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network
  backend:
    container_name: foodgram_backend
    image: awesomegoose/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/web
      - media:/app/media
      - redoc:/app/api/docs/
    networks:
      - foodgram_network
  frontend:
    container_name: foodgram_front
    image: awesomegoose/foodgram_frontend:latest
    volumes:
      - static:/app/frontend_static
    command: cp -r /app/build/. /app/frontend_static
    networks:
      - foodgram_network
  gateway:
    container_name: foodgram_gateway
    image: awesomegoose/foodgram_proxy:latest
    depends_on:
      - backend
    ports:
      - 8001:80
    volumes:
      - static:/web
      - media:/web/media
      - redoc:/app/api/docs
    networks:
      - foodgram_network