version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
networks:
  foodgram_network:
    driver: bridge

services:

  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network

  backend:
    container_name: foodgram_backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    ports:
      - "8105:8000"
    networks:
      - foodgram_network

  frontend:
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - ./frontend/:/app/result_build/
    networks:
      - foodgram_network

  nginx:
    container_name: foodgram-proxy
    build: ./nginx/
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - static:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media
    networks:
      - foodgram_network
