# Generated by Django 4.1 on 2024-09-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_password_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.SlugField(blank=True),
        ),
    ]
