# Generated by Django 4.1 on 2024-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
